service: passei-direto

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 60
  memorySize: 2048
  environment:
    DATA_SOURCE_BUCKET_NAME: ${self:custom.dataSourceBucketName}
    DATA_WAREHOUSE_BUCKET_NAME: ${self:custom.dataWarehouseBucketName}
    TABLE_REFRESHER_CRAWLER_NAME: ${self:custom.tableRefresherCrawlerName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - ${self:custom.dataSourceBucketName}
              - '/*'
        - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - ${self:custom.dataWarehouseBucketName}
              - '/*'
    - Effect: Allow
      Action:
        - glue:StartCrawler
      Resource:
        - Fn::Join:
            - ''
            - - 'arn:aws:glue:'
              - ${self:provider.region}
              - ':'
              - !Ref AWS::AccountId
              - ':crawler/'
              - ${self:custom.tableRefresherCrawlerName}

package:
  exclude:
    - test

custom:
  dataSourceBucketName: ${env:DATA_SOURCE_BUCKET_NAME, 'mocked.data.source'}
  dataWarehouseBucketName: ${self:provider.stage}.data.warehouse
  dataWarehouseDatabaseName: ${self:provider.stage}-data-warehouse-database
  tableRefresherCrawlerName: ${self:provider.stage}-table-refresher-crawler
  tableRefresherRoleName: ${self:provider.stage}-table-refresher-crawler-role-${self:provider.region}

functions:
  extractTransformLoad:
    handler: src/handler.extractTransformLoad
    events:
      - sns: ${self:provider.stage}-trigger-etl

resources:
  Resources:
    DataWarehouseBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.dataWarehouseBucketName}
    TableRefresherCrawler:
      Type: AWS::Glue::Crawler
      Properties:
        Name: ${self:custom.tableRefresherCrawlerName}
        Targets:
          S3Targets:
            - Path: s3://${self:custom.dataWarehouseBucketName}/
        DatabaseName: !Ref DataWarehouseDatabase
        Role: !GetAtt TableRefresherRole.Arn
      DependsOn:
        - DataWarehouseDatabase
        - TableRefresherRole
    DataWarehouseDatabase:
      Type: AWS::Glue::Database
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseInput:
          Name: ${self:custom.dataWarehouseDatabaseName}
    TableRefresherRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - glue.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.tableRefresherRoleName}
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                  Resource:
                    - !GetAtt [DataWarehouseBucket, Arn]
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
