version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    docker:
      - image: circleci/node:12.13
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
